export const skillsByDepartment = {
  Engineering: [
    "Python",
    "Go",
    "Kubernetes",
    "REST API Development",
    "Cloud Architecture",
    "System Design",
    "Testing Automation",
    "Agile Practices",
    "Data Structures & Algorithms",
  ],
  Marketing: [
    "Market Research",
    "Campaign Management",
    "Facebook Ads",
    "Public Relations",
    "Influencer Outreach",
    "Event Planning",
    "Creative Strategy",
    "Analytics Reporting",
  ],
  Sales: [
    "Pipeline Management",
    "Prospecting",
    "Product Demos",
    "Account Management",
    "Contract Negotiation",
    "Sales Forecasting",
    "Client Retention",
    "Opportunity Tracking",
  ],
  HR: [
    "Talent Acquisition",
    "Employee Engagement",
    "HRIS Systems",
    "Compensation Planning",
    "Policy Development",
    "Workplace Safety",
    "Training Programs",
  ],
  Finance: [
    "Risk Management",
    "Investment Analysis",
    "Cost Control",
    "Accounts Payable",
    "Auditing",
    "Financial Modeling",
    "Budget Forecasting",
    "Capital Management",
  ],
};
